import './globals.css' // Needs to be at the top of the file

import '@mantine/core/styles.css'

import { ColorSchemeScript, MantineProvider } from '@mantine/core'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider defaultColorScheme='dark'>{children}</MantineProvider>
      </body>
    </html>
  )
}
